### ISSUE TITLE
Support for list grains

### ISSUE THREAD

**Issue by mchugh19** [carlpett/salt-vault#14]
It would be great if the policy mapping code could support list grains. 

In the case of:
`saltstack/minion/{grains[ec2_tags][Environment]}/{grains[ec2_roles]}`

the ec2_roles grain is a list assigned from AWS tags. As such, it would be useful to have vault policies assigned for each value in the list. As it is this maps to:
```
# salt-run vault.show_policies ip-10-241-1-117.ec2.internal
- saltstack/minions
- saltstack/minion/ip-10-241-1-117.ec2.internal
- saltstack/minion/crankcase/['landingzone', 'clusternode']
```

Where, it would be helpful to have it map instead to:
```
...
- saltstack/minion/crankcase/landingzone
- saltstack/minion/crankcase/clusternode
```

**Comment by mchugh19** [comment]
I don't see an easy way of accomplishing this. Any thoughts?

**Comment by carlpett** [comment]
No, I've been thinking about it the last days, and it might be complicated. We'd have to do the tokenization  ourselves instead of just running string format with a splatted dict. Not impossible of course, but significantly more complicated than the current implementation.

**Comment by mchugh19** [comment]
Is it too ugly of a hack to perform the tokenization and then evaluate the list?

```
for x in re.findall(r"{.*?}", pattern):
  mapped = x.format(**mappings)
  print("Mapped {0}".format(mapped))
  if mapped.startswith("["):
    mapped = ast.literal_eval(mapped)
    for listitem in mapped:
      print listitem
```

**Comment by carlpett** [comment]
I think the approach would be to tokenize, then for each token get it from the grains dictionary, then do some type checking and handle lists (and possibly dictionaries?) as cases which yield multiple outputs. String-matching on "[" feels a bit brittle.
I had a look at the python source to see if there was an easy way to reuse their tokenization, but it wasn't entierly simple to extract. I might give it a shot next week, because the idea seems quite useful.
